/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'course-holes': CourseHole;
    tournaments: Tournament;
    rooms: Room;
    tariffs: Tariff;
    contacts: Contact;
    'affiliated-clubs': AffiliatedClub;
    'committee-members': CommitteeMember;
    newsletters: Newsletter;
    stories: Story;
    'tee-time-requests': TeeTimeRequest;
    'room-enquiries': RoomEnquiry;
    'dining-enquiries': DiningEnquiry;
    'membership-enquiries': MembershipEnquiry;
    'tournament-registrations': TournamentRegistration;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'course-holes': CourseHolesSelect<false> | CourseHolesSelect<true>;
    tournaments: TournamentsSelect<false> | TournamentsSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    tariffs: TariffsSelect<false> | TariffsSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    'affiliated-clubs': AffiliatedClubsSelect<false> | AffiliatedClubsSelect<true>;
    'committee-members': CommitteeMembersSelect<false> | CommitteeMembersSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    'tee-time-requests': TeeTimeRequestsSelect<false> | TeeTimeRequestsSelect<true>;
    'room-enquiries': RoomEnquiriesSelect<false> | RoomEnquiriesSelect<true>;
    'dining-enquiries': DiningEnquiriesSelect<false> | DiningEnquiriesSelect<true>;
    'membership-enquiries': MembershipEnquiriesSelect<false> | MembershipEnquiriesSelect<true>;
    'tournament-registrations': TournamentRegistrationsSelect<false> | TournamentRegistrationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'course-status': CourseStatus;
    'course-info': CourseInfo;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'course-status': CourseStatusSelect<false> | CourseStatusSelect<true>;
    'course-info': CourseInfoSelect<false> | CourseInfoSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-holes".
 */
export interface CourseHole {
  id: number;
  holeNumber: number;
  /**
   * Confirm official spelling, capitalisation and apostrophes with the golf committee.
   */
  officialName: string;
  par: number;
  strokeIndex?: number | null;
  /**
   * Yards, from the men’s tees.
   */
  mensDistance?: number | null;
  /**
   * Yards, from the women’s tees.
   */
  womensDistance?: number | null;
  /**
   * Metres, tee to green. Negative = downhill.
   */
  elevationChange?: number | null;
  additionalTees?:
    | {
        teeName: string;
        distance: number;
        id?: string | null;
      }[]
    | null;
  /**
   * The hole’s story. Preserve the personality of the legacy description while keeping it accurate and readable.
   */
  overview: string;
  teeShotStrategy: string;
  approachStrategy?: string | null;
  greenStrategy?: string | null;
  captainTip?: string | null;
  localRule?: string | null;
  hazards?:
    | {
        hazardType: 'bunker' | 'water' | 'out-of-bounds' | 'trees' | 'rough' | 'slope' | 'other';
        position?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  primaryImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  holeDiagram?: (number | null) | Media;
  aerialImage?: (number | null) | Media;
  /**
   * A plain-language description of the hole for screen-reader users.
   */
  accessibilityDescription?: string | null;
  /**
   * Content marked "Pending" is treated as unverified and is hidden or softened on the public site.
   */
  verification: {
    status: 'pending' | 'verified';
    verifiedBy?: string | null;
    verifiedOn?: string | null;
    /**
     * Internal notes only. Never shown publicly.
     */
    notes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alt text, e.g. "A mist-covered fairway at Mercara Downs Golf Club framed by mature trees." Never a file name.
   */
  alt: string;
  caption?: string | null;
  copyrightOwner?: string | null;
  usagePermission?: ('confirmed' | 'unconfirmed') | null;
  /**
   * Archival images are labelled with an approximate date on the site.
   */
  isArchival?: boolean | null;
  /**
   * e.g. "circa 1975" — shown when the image is archival.
   */
  approximateDate?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments".
 */
export interface Tournament {
  id: number;
  name: string;
  year: number;
  startDate?: string | null;
  endDate?: string | null;
  status:
    | 'draft'
    | 'announced'
    | 'registration-open'
    | 'registration-closed'
    | 'draw-published'
    | 'in-progress'
    | 'results-published'
    | 'postponed'
    | 'cancelled'
    | 'archived';
  sponsor?: string | null;
  /**
   * e.g. 18-hole Stableford
   */
  format?: string | null;
  eligibility?: string | null;
  /**
   * INR, excluding taxes.
   */
  entryFee?: number | null;
  handicapRule?: string | null;
  maximumField?: number | null;
  registrationDeadline?: string | null;
  drawDocument?: (number | null) | Media;
  teeTimesDocument?: (number | null) | Media;
  winners?:
    | {
        category: string;
        playerName: string;
        score?: string | null;
        id?: string | null;
      }[]
    | null;
  report?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  resultsDocument?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  documents?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Content marked "Pending" is treated as unverified and is hidden or softened on the public site.
   */
  verification: {
    status: 'pending' | 'verified';
    verifiedBy?: string | null;
    verifiedOn?: string | null;
    /**
     * Internal notes only. Never shown publicly.
     */
    notes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  roomName: string;
  capacity: number;
  bedType?: ('double' | 'twin' | 'family' | 'suite') | null;
  view?: ('course' | 'garden' | 'other') | null;
  description?: string | null;
  amenities?:
    | {
        amenity: string;
        id?: string | null;
      }[]
    | null;
  accessibilityInformation?: string | null;
  /**
   * e.g. 12:00 noon
   */
  checkIn?: string | null;
  /**
   * e.g. 11:00 a.m.
   */
  checkOut?: string | null;
  tariff?: {
    /**
     * INR per night, excluding taxes.
     */
    currentTariff?: number | null;
    /**
     * e.g. plus 12% GST
     */
    taxNote?: string | null;
    guestCategory?: ('member' | 'affiliated' | 'member-guest' | 'visitor')[] | null;
    effectiveDate?: string | null;
    /**
     * Tariff is flagged on the site once this date passes.
     */
    reviewDate?: string | null;
  };
  gallery?: (number | Media)[] | null;
  policies?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  displayOrder?: number | null;
  /**
   * Content marked "Pending" is treated as unverified and is hidden or softened on the public site.
   */
  verification: {
    status: 'pending' | 'verified';
    verifiedBy?: string | null;
    verifiedOn?: string | null;
    /**
     * Internal notes only. Never shown publicly.
     */
    notes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tariffs".
 */
export interface Tariff {
  id: number;
  /**
   * e.g. "Green fee — 18 holes, affiliated-club visitor"
   */
  label: string;
  category:
    'green-fee' | 'caddy' | 'buggy' | 'rental' | 'coaching' | 'room' | 'membership' | 'tournament-entry' | 'other';
  visitorCategory?: ('member' | 'affiliated' | 'member-guest' | 'visitor' | 'tournament')[] | null;
  /**
   * INR, excluding taxes.
   */
  amount: number;
  /**
   * e.g. per round, per night, per hour
   */
  unit?: string | null;
  /**
   * e.g. "plus applicable taxes" or "plus 12% GST"
   */
  taxNote: string;
  effectiveDate: string;
  /**
   * Rate is flagged/hidden on the site after this date until re-confirmed.
   */
  reviewDate: string;
  /**
   * Internal person responsible for keeping this rate current.
   */
  contentOwner: string;
  notes?: string | null;
  /**
   * Content marked "Pending" is treated as unverified and is hidden or softened on the public site.
   */
  verification: {
    status: 'pending' | 'verified';
    verifiedBy?: string | null;
    verifiedOn?: string | null;
    /**
     * Internal notes only. Never shown publicly.
     */
    notes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  department:
    | 'club-reception'
    | 'golf-operations'
    | 'tee-time-enquiries'
    | 'general-manager'
    | 'membership'
    | 'tournament-office'
    | 'downs-retreat'
    | 'room-reservations'
    | 'dining-reservations'
    | 'accounts'
    | 'coaching'
    | 'emergency';
  contactPerson?: string | null;
  designation?: string | null;
  phone?: string | null;
  whatsappAvailable?: boolean | null;
  email?: string | null;
  workingHours?: string | null;
  /**
   * Personal staff numbers must not be published without explicit approval.
   */
  publicStatus: 'public' | 'internal';
  lastVerified?: string | null;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliated-clubs".
 */
export interface AffiliatedClub {
  id: number;
  clubName: string;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  website?: string | null;
  /**
   * Link the applicable reciprocal fee record, if any.
   */
  reciprocalGreenFee?: (number | null) | Tariff;
  notes?: string | null;
  /**
   * Content marked "Pending" is treated as unverified and is hidden or softened on the public site.
   */
  verification: {
    status: 'pending' | 'verified';
    verifiedBy?: string | null;
    verifiedOn?: string | null;
    /**
     * Internal notes only. Never shown publicly.
     */
    notes?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committee-members".
 */
export interface CommitteeMember {
  id: number;
  name: string;
  /**
   * e.g. President, Captain, Honorary Secretary
   */
  designation: string;
  photograph?: (number | null) | Media;
  termStart?: string | null;
  termEnd?: string | null;
  /**
   * When a term ends, set to Former — past members move to the archive rather than disappearing.
   */
  memberStatus: 'active' | 'former';
  biography?: string | null;
  /**
   * Personal telephone numbers are never shown unless explicitly approved.
   */
  publicContact?: boolean | null;
  contact?: (number | null) | Contact;
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  title: string;
  year: number;
  edition?: string | null;
  publicationDate?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Short accessible summary shown on the archive page — never a blank page with only an embed.
   */
  summary: string;
  featuredStories?:
    | {
        story: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optimised PDF with a meaningful file name.
   */
  pdf?: (number | null) | Media;
  /**
   * Accessible HTML version of the highlights.
   */
  htmlSummary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  /**
   * URL segment, e.g. monsoon-medal-2026
   */
  slug: string;
  category:
    | 'tournament-report'
    | 'member-story'
    | 'course-story'
    | 'junior-golf'
    | 'caddy-story'
    | 'heritage'
    | 'announcement'
    | 'newsletter';
  publishedDate: string;
  excerpt: string;
  heroImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tee-time-requests".
 */
export interface TeeTimeRequest {
  id: number;
  playerCategory: 'member' | 'affiliated' | 'member-guest' | 'visitor' | 'tournament';
  preferredDate: string;
  alternativeDate?: string | null;
  numberOfGolfers: number;
  holes: '9' | '18';
  preferredTimeRange?: string | null;
  caddyRequired?: boolean | null;
  buggyRequired?: boolean | null;
  rentalClubsRequired?: boolean | null;
  fullName: string;
  mobile: string;
  email: string;
  homeClub?: string | null;
  handicap?: string | null;
  affiliationDetails?: string | null;
  /**
   * Required for member guests.
   */
  memberHost?: string | null;
  notes?: string | null;
  enquiryStatus: 'new' | 'in-progress' | 'confirmed' | 'declined' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "room-enquiries".
 */
export interface RoomEnquiry {
  id: number;
  checkInDate: string;
  checkOutDate: string;
  numberOfRooms: number;
  adults: number;
  children?: number | null;
  guestCategory: 'member' | 'affiliated' | 'member-guest' | 'visitor' | 'tournament';
  golfRequired?: boolean | null;
  diningRequired?: boolean | null;
  fullName: string;
  mobile: string;
  email: string;
  notes?: string | null;
  enquiryStatus: 'new' | 'in-progress' | 'confirmed' | 'declined' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dining-enquiries".
 */
export interface DiningEnquiry {
  id: number;
  diningDate: string;
  preferredTime: string;
  partySize: number;
  guestCategory: 'member' | 'affiliated' | 'member-guest' | 'visitor' | 'tournament';
  fullName: string;
  mobile: string;
  email: string;
  dietaryNotes?: string | null;
  notes?: string | null;
  enquiryStatus: 'new' | 'in-progress' | 'confirmed' | 'declined' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-enquiries".
 */
export interface MembershipEnquiry {
  id: number;
  fullName: string;
  mobile: string;
  email: string;
  city?: string | null;
  homeClub?: string | null;
  handicap?: string | null;
  message?: string | null;
  enquiryStatus: 'new' | 'in-progress' | 'confirmed' | 'declined' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-registrations".
 */
export interface TournamentRegistration {
  id: number;
  /**
   * Registrations are accepted only while a tournament is in "Registration Open".
   */
  tournament: number | Tournament;
  fullName: string;
  mobile: string;
  email: string;
  homeClub?: string | null;
  handicap: string;
  affiliationDetails?: string | null;
  notes?: string | null;
  enquiryStatus: 'new' | 'in-progress' | 'confirmed' | 'declined' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'course-holes';
        value: number | CourseHole;
      } | null)
    | ({
        relationTo: 'tournaments';
        value: number | Tournament;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'tariffs';
        value: number | Tariff;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'affiliated-clubs';
        value: number | AffiliatedClub;
      } | null)
    | ({
        relationTo: 'committee-members';
        value: number | CommitteeMember;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'tee-time-requests';
        value: number | TeeTimeRequest;
      } | null)
    | ({
        relationTo: 'room-enquiries';
        value: number | RoomEnquiry;
      } | null)
    | ({
        relationTo: 'dining-enquiries';
        value: number | DiningEnquiry;
      } | null)
    | ({
        relationTo: 'membership-enquiries';
        value: number | MembershipEnquiry;
      } | null)
    | ({
        relationTo: 'tournament-registrations';
        value: number | TournamentRegistration;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-holes_select".
 */
export interface CourseHolesSelect<T extends boolean = true> {
  holeNumber?: T;
  officialName?: T;
  par?: T;
  strokeIndex?: T;
  mensDistance?: T;
  womensDistance?: T;
  elevationChange?: T;
  additionalTees?:
    | T
    | {
        teeName?: T;
        distance?: T;
        id?: T;
      };
  overview?: T;
  teeShotStrategy?: T;
  approachStrategy?: T;
  greenStrategy?: T;
  captainTip?: T;
  localRule?: T;
  hazards?:
    | T
    | {
        hazardType?: T;
        position?: T;
        description?: T;
        id?: T;
      };
  primaryImage?: T;
  gallery?: T;
  holeDiagram?: T;
  aerialImage?: T;
  accessibilityDescription?: T;
  verification?:
    | T
    | {
        status?: T;
        verifiedBy?: T;
        verifiedOn?: T;
        notes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments_select".
 */
export interface TournamentsSelect<T extends boolean = true> {
  name?: T;
  year?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  sponsor?: T;
  format?: T;
  eligibility?: T;
  entryFee?: T;
  handicapRule?: T;
  maximumField?: T;
  registrationDeadline?: T;
  drawDocument?: T;
  teeTimesDocument?: T;
  winners?:
    | T
    | {
        category?: T;
        playerName?: T;
        score?: T;
        id?: T;
      };
  report?: T;
  resultsDocument?: T;
  gallery?: T;
  documents?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  verification?:
    | T
    | {
        status?: T;
        verifiedBy?: T;
        verifiedOn?: T;
        notes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  roomName?: T;
  capacity?: T;
  bedType?: T;
  view?: T;
  description?: T;
  amenities?:
    | T
    | {
        amenity?: T;
        id?: T;
      };
  accessibilityInformation?: T;
  checkIn?: T;
  checkOut?: T;
  tariff?:
    | T
    | {
        currentTariff?: T;
        taxNote?: T;
        guestCategory?: T;
        effectiveDate?: T;
        reviewDate?: T;
      };
  gallery?: T;
  policies?: T;
  displayOrder?: T;
  verification?:
    | T
    | {
        status?: T;
        verifiedBy?: T;
        verifiedOn?: T;
        notes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tariffs_select".
 */
export interface TariffsSelect<T extends boolean = true> {
  label?: T;
  category?: T;
  visitorCategory?: T;
  amount?: T;
  unit?: T;
  taxNote?: T;
  effectiveDate?: T;
  reviewDate?: T;
  contentOwner?: T;
  notes?: T;
  verification?:
    | T
    | {
        status?: T;
        verifiedBy?: T;
        verifiedOn?: T;
        notes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  department?: T;
  contactPerson?: T;
  designation?: T;
  phone?: T;
  whatsappAvailable?: T;
  email?: T;
  workingHours?: T;
  publicStatus?: T;
  lastVerified?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliated-clubs_select".
 */
export interface AffiliatedClubsSelect<T extends boolean = true> {
  clubName?: T;
  city?: T;
  state?: T;
  country?: T;
  website?: T;
  reciprocalGreenFee?: T;
  notes?: T;
  verification?:
    | T
    | {
        status?: T;
        verifiedBy?: T;
        verifiedOn?: T;
        notes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committee-members_select".
 */
export interface CommitteeMembersSelect<T extends boolean = true> {
  name?: T;
  designation?: T;
  photograph?: T;
  termStart?: T;
  termEnd?: T;
  memberStatus?: T;
  biography?: T;
  publicContact?: T;
  contact?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  edition?: T;
  publicationDate?: T;
  coverImage?: T;
  summary?: T;
  featuredStories?:
    | T
    | {
        story?: T;
        id?: T;
      };
  pdf?: T;
  htmlSummary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedDate?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tee-time-requests_select".
 */
export interface TeeTimeRequestsSelect<T extends boolean = true> {
  playerCategory?: T;
  preferredDate?: T;
  alternativeDate?: T;
  numberOfGolfers?: T;
  holes?: T;
  preferredTimeRange?: T;
  caddyRequired?: T;
  buggyRequired?: T;
  rentalClubsRequired?: T;
  fullName?: T;
  mobile?: T;
  email?: T;
  homeClub?: T;
  handicap?: T;
  affiliationDetails?: T;
  memberHost?: T;
  notes?: T;
  enquiryStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "room-enquiries_select".
 */
export interface RoomEnquiriesSelect<T extends boolean = true> {
  checkInDate?: T;
  checkOutDate?: T;
  numberOfRooms?: T;
  adults?: T;
  children?: T;
  guestCategory?: T;
  golfRequired?: T;
  diningRequired?: T;
  fullName?: T;
  mobile?: T;
  email?: T;
  notes?: T;
  enquiryStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dining-enquiries_select".
 */
export interface DiningEnquiriesSelect<T extends boolean = true> {
  diningDate?: T;
  preferredTime?: T;
  partySize?: T;
  guestCategory?: T;
  fullName?: T;
  mobile?: T;
  email?: T;
  dietaryNotes?: T;
  notes?: T;
  enquiryStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-enquiries_select".
 */
export interface MembershipEnquiriesSelect<T extends boolean = true> {
  fullName?: T;
  mobile?: T;
  email?: T;
  city?: T;
  homeClub?: T;
  handicap?: T;
  message?: T;
  enquiryStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-registrations_select".
 */
export interface TournamentRegistrationsSelect<T extends boolean = true> {
  tournament?: T;
  fullName?: T;
  mobile?: T;
  email?: T;
  homeClub?: T;
  handicap?: T;
  affiliationDetails?: T;
  notes?: T;
  enquiryStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  copyrightOwner?: T;
  usagePermission?: T;
  isArchival?: T;
  approximateDate?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-status".
 */
export interface CourseStatus {
  id: number;
  courseStatus: 'open' | 'restricted' | 'closed';
  /**
   * e.g. "First tee available from 6:30 a.m."
   */
  firstTeeStatus?: string | null;
  /**
   * e.g. "Morning mist, clearing by 9 a.m."
   */
  weatherNote?: string | null;
  caddyAvailability?: ('available' | 'limited' | 'unavailable') | null;
  buggyAvailability?: ('available' | 'limited' | 'unavailable') | null;
  practiceAreaStatus?: ('open' | 'closed') | null;
  diningStatus?: ('open' | 'closed') | null;
  /**
   * Optional short notice, e.g. maintenance on holes 6–8.
   */
  noticeToGolfers?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-info".
 */
export interface CourseInfo {
  id: number;
  numberOfHoles?: number | null;
  coursePar?: number | null;
  mensYardage?: number | null;
  womensYardage?: number | null;
  courseRating?: number | null;
  slopeRating?: number | null;
  totalAcreage?: number | null;
  /**
   * Metres above sea level — publish only if verified.
   */
  elevationMetres?: number | null;
  /**
   * Legacy site coordinates pointed to Bengaluru — do not reuse.
   */
  latitude?: number | null;
  longitude?: number | null;
  greenGrass?: string | null;
  fairwayGrass?: string | null;
  roughGrass?: string | null;
  numberOfBunkers?: number | null;
  numberOfWaterHazards?: number | null;
  courseRecord?: string | null;
  services?: {
    caddiesAvailable?: boolean | null;
    buggiesAvailable?: boolean | null;
    rentalClubsAvailable?: boolean | null;
    practiceFacilities?: boolean | null;
    coachingAvailable?: boolean | null;
  };
  landscapeCharacter?: string | null;
  /**
   * Content marked "Pending" is treated as unverified and is hidden or softened on the public site.
   */
  verification: {
    status: 'pending' | 'verified';
    verifiedBy?: string | null;
    verifiedOn?: string | null;
    /**
     * Internal notes only. Never shown publicly.
     */
    notes?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  clubName?: string | null;
  tagline?: string | null;
  /**
   * The single verified historical statement used across the site. Do not claim a precise founding year unless the club can document it.
   */
  heritageStatement?: string | null;
  address?: {
    line1?: string | null;
    line2?: string | null;
    town?: string | null;
    district?: string | null;
    state?: string | null;
    pincode?: string | null;
  };
  /**
   * Journey rows for the Directions section — all times must be verified.
   */
  directions?:
    | {
        origin: string;
        approximateDistance?: string | null;
        approximateTime?: string | null;
        /**
         * Unverified rows are not shown publicly.
         */
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * "Open in Maps" link — must point at the verified club location.
   */
  mapsUrl?: string | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-status_select".
 */
export interface CourseStatusSelect<T extends boolean = true> {
  courseStatus?: T;
  firstTeeStatus?: T;
  weatherNote?: T;
  caddyAvailability?: T;
  buggyAvailability?: T;
  practiceAreaStatus?: T;
  diningStatus?: T;
  noticeToGolfers?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-info_select".
 */
export interface CourseInfoSelect<T extends boolean = true> {
  numberOfHoles?: T;
  coursePar?: T;
  mensYardage?: T;
  womensYardage?: T;
  courseRating?: T;
  slopeRating?: T;
  totalAcreage?: T;
  elevationMetres?: T;
  latitude?: T;
  longitude?: T;
  greenGrass?: T;
  fairwayGrass?: T;
  roughGrass?: T;
  numberOfBunkers?: T;
  numberOfWaterHazards?: T;
  courseRecord?: T;
  services?:
    | T
    | {
        caddiesAvailable?: T;
        buggiesAvailable?: T;
        rentalClubsAvailable?: T;
        practiceFacilities?: T;
        coachingAvailable?: T;
      };
  landscapeCharacter?: T;
  verification?:
    | T
    | {
        status?: T;
        verifiedBy?: T;
        verifiedOn?: T;
        notes?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  clubName?: T;
  tagline?: T;
  heritageStatement?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        town?: T;
        district?: T;
        state?: T;
        pincode?: T;
      };
  directions?:
    | T
    | {
        origin?: T;
        approximateDistance?: T;
        approximateTime?: T;
        verified?: T;
        id?: T;
      };
  mapsUrl?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}